USE [master]
GO
/****** Object:  Database [ThinkBridgeDB]    Script Date: 16-Sep-20 6:02:43 PM ******/
CREATE DATABASE [ThinkBridgeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ThinkBridgeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SDCSERVER\MSSQL\DATA\ThinkBridgeDB.mdf' , SIZE = 5312KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ThinkBridgeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SDCSERVER\MSSQL\DATA\ThinkBridgeDB_log.ldf' , SIZE = 5824KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ThinkBridgeDB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ThinkBridgeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ThinkBridgeDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ThinkBridgeDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ThinkBridgeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ThinkBridgeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ThinkBridgeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ThinkBridgeDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ThinkBridgeDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ThinkBridgeDB] SET  MULTI_USER 
GO
ALTER DATABASE [ThinkBridgeDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ThinkBridgeDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ThinkBridgeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ThinkBridgeDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ThinkBridgeDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ThinkBridgeDB]
GO
/****** Object:  Table [dbo].[Inventory]    Script Date: 16-Sep-20 6:02:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Inventory](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
	[Description] [nvarchar](max) NULL,
	[Image] [nvarchar](max) NULL,
	[Price] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Inventory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ThinkBridgeDB] SET  READ_WRITE 
GO
